### ISSUE TITLE
Project name in use

### ISSUE THREAD

**Issue by carc1n0gen** [BlueBayTravel/Phrontmatter#1]
Hi, sorry to be "that guy", but this name is already in use: https://github.com/carc1n0gen/PhrontMatter.  It doesn't bother me all that much, but it would be nice if you thought of a different name.

**Comment by vinkla** [comment]
Why? With prefixed vendor names the name doesn't matter? Isn't that what makes composer better than similar tools like npm?

**Comment by vinkla** [comment]
I've a project named Facebook and I know that is taken. Same goes for most of my packages to be honest.

**Comment by carc1n0gen** [comment]
Can't blame a guy for trying :P

**Comment by carc1n0gen** [comment]
Can't blame a guy for trying :P

**Comment by jbrooksuk** [comment]
I noticed this afterwards, but it doesn't matter too much at all, as @vinkla said, that's why we have prefixes :)
