### ISSUE TITLE
Add support for other serialization of front matter

### ISSUE THREAD

**Issue by carbontwelve** [BlueBayTravel/Phrontmatter#3]
While YAML is wildly popular, with a few small amends it would be trivial to add support for many serialization formats (e.g. JSON, flat ini type, TOML, etc.) Personally I would only use YAML or TOML but abstracting the front matter parser would open this project to more use cases.

**Comment by jbrooksuk** [comment]
How would you know what serialization is in use? Maybe something that would allow this?

<pre>
```json
{
    //
}
```
</pre>

Or

<pre>
```yaml
foo: bar
```
</pre>

**Comment by carbontwelve** [comment]
When I wrote the issue I thought the easiest way of doing so would be to have a second argument on the `parse` method such as `public function parse($content, $format = null) { .. }`. Where a non `null` answer might be for example an implementation of a new `PhrontmatterFormat` Interface.

Such an abstraction could work by adding `PhrontmatterFormat.php` with the content:

``` php
<?php

namespace BlueBayTravel\Phrontmatter;

interface PhrontmatterFormat {

    public function deserialise($input);

}
```

Then each serialization format would have its own class, for example in a new `Formats` folder the YAML one might be:

``` php
<?php

namespace BlueBayTravel\Phrontmatter\Formats;

use Symfony\Component\Yaml\Yaml;

class YAMLFormat implements BlueBayTravel\Phrontmatter\PhrontmatterFormat {

    public function deserialise($input) {
        return Yaml::parse($input);
    }

}
```

and a JSON one might be:

``` php
<?php

namespace BlueBayTravel\Phrontmatter\Formats;

class JSONFormat implements BlueBayTravel\Phrontmatter\PhrontmatterFormat {

    public function deserialise($input) {
        return json_decode($input);
    }

}
```

Once this abstraction is implemented the regular usage of the parse method would simply default to using the `YAMLFormat` class when its `$format` attribute is null. Alternatively `$format` could either be an instance of the FormatClass (e.g: `parse($string, new \BlueBayTravel\Phrontmatter\Formats\JSONFormat())`), or its namespaced name (e.g: `parse($string, \BlueBayTravel\Phrontmatter\Formats\JSONFormat::class)`) or loaded by a new factory... 

This would allow anyone using Phrontmatter to write their own Format implementation if the project didn't contain the exotic one they were using.

Just some ideas :smile:

**Comment by jbrooksuk** [comment]
Ok, yeah makes sense.

Rather than passing through the format class, I'd rather something like `Phrontmatter::JSON` as a constant value.

**Comment by jbrooksuk** [comment]
I'll implement this when I get a bit of free time :+1:

**Comment by carbontwelve** [comment]
You can have a new 1.0.1 release now :+1:

**Comment by jbrooksuk** [comment]
I'll do 1.1
